//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace StefaniniPhoneBook
{
    using System;
    using System.Collections.Generic;
    
    public partial class DetailType
    {
        public DetailType()
        {
            this.Details = new HashSet<Detail>();
        }
    
        public int ID { get; set; }
        public string DetailTypeData { get; set; }
    
        public virtual ICollection<Detail> Details { get; set; }
    }
}
